/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 13:16:21 GMT 2018
 */

package exception;

import org.junit.Test;
import static org.junit.Assert.*;
import exception.CampoObrigatorioException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CampoObrigatorioException_ESTest extends CampoObrigatorioException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CampoObrigatorioException campoObrigatorioException0 = new CampoObrigatorioException("");
  }
}
